project:
  type: website
  output-dir: "docs"
  resources: 
    - Resume.pdf
  preview: 
    port: 5555
    browser: true
    watch-inputs: true
    navigate: true

website:
  title: "Dane Winterboer"
  navbar:
    left:
      - text: "Portfolio"
        file: "portfolio/index.qmd"
      - text: "Consulting"
        file: "consulting/index.qmd"
      - text: "Résumé"
        file: "cv/index.qmd"
    right:
      - text: "About"
        file: index.qmd
      - icon: github
        href: https://github.com/DaneWinter
        target: _blank
      - icon: linkedin
        href: https://www.linkedin.com/in/dane-winterboer-965554259
        target: _blank

format:
  html:
    theme: flatly
    css: styles.css

editor: visual

